---
title: "Constructing Trees from Alignments"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reading Tree Structures and Preliminaries

```{r}
#Reconstructing trees from alignments using phangorn

library(Biostrings)
library(msa)
library(phangorn)

remote_dir="https://raw.githubusercontent.com/PacktPublishing/R-Bioinformatics-Cookbook/master"
seqs <- readAAStringSet(file.path(remote_dir, "datasets", "ch4", "abc.fa"))
```

## Aligning Sequences

```{r}
aln <- msa::msa(seqs, method=c("ClustalOmega"))
```

## Contructing Trees from Alignment

```{r}
aln <- as.phyDat(aln, type = "AA")
dist_mat <- dist.ml(aln)
upgma_tree <- upgma(dist_mat)
plot(upgma_tree, main="UPGMA")
```

## Neighbor Joinging trees

```{r}
nj_tree <- NJ(dist_mat)
plot(nj_tree,"unrooted", main="NJ")
```

## Boostrapping

```{r}
fit <- pml(nj_tree, aln)
bootstraps <- bootstrap.phyDat(aln,FUN=function(x) { NJ(dist.ml(x)) } , bs=100)
plotBS(nj_tree, bootstraps, p = 10)
```
